import { Inter } from "next/font/google";
import "./globals.css";
import Header from "@/components/ui/header";
import { ClerkProvider } from "@clerk/nextjs";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "CapitalFlow",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <ClerkProvider>
      <html lang="en" suppressHydrationWarning>
        <body className={`${inter.className} min-h-dvh flex flex-col`}>
          {/* Header */}
          <Header />

          {/* Main grows to push footer down */}
          <main className="flex-1">
            {children}
          </main>

          {/* Footer */}
          <footer className="bg-blue-50 py-12">
            <div className="container mx-auto px-4 text-center text-gray-600">
              <p>Made by Shashank Soni</p>
            </div>
          </footer>
        </body>
      </html>
    </ClerkProvider>
  );
}