import { Inter } from "next/font/google";
import "./globals.css";
import { headers } from "next/headers";
import { Footer } from "react-day-picker";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Wealth Tracker",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${inter.className}`}
      >
        {
          // header
        }
        {children}
        {//Footer
        }
        <footer className="bg-blue-50 py-12">
          <div>
            <p>
              Made by Shashank Soni
            </p>
          </div>
        </footer>
      </body>
    </html>
  );
}
